mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^new/$', views.new, name='new'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateView.as_view(), name='update'),
	url(r'^(?P<pk>[0-9]+)/delete/$', views.UpdateView.as_view(), name='delete'),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
	question_text = models.CharField(max_length = 200, unique=True)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)
	def __str__(self):
		return self.choice_text

mysite/polls/forms.py
from django import forms
from .models import Question, Choice

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = "__all__"
		exclude = ["votes",]


class ChoiceForm(forms.ModelForm):
	class Meta:
		model = Choice
		fields = "__all__"

mysite/polls/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.forms.models import inlineformset_factory

from .models import Question, Choice
from .forms import QuestionForm
from django.views.generic.edit import UpdateView, DeleteView


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
			Return the last five published questions (not including those set to be
			published in the future)
		"""
		return Question.objects.filter(
					pub_date__lte =  timezone.now()
				).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
			excludes questions that not are published yet
		"""
		return Question.objects.filter( pub_date__lte = timezone.now )


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'


def vote(request, question_id):
	p = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'polls/detail.html', {
			'question': p,
			'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
	return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


class UpdateView(UpdateView):
	model = Question
	fields = ["question_text"]
	template_name = 'polls/update.html'

	def post(self, *args, **kwargs):
		self.success_url = reverse_lazy('polls:detail', args=(kwargs['pk'],))
		return super(UpdateView, self).post(*args, **kwargs)


def new(request):
	question = Question()
	ChoiceInlineFormSet = inlineformset_factory(Question, Choice, form=QuestionForm, extra=2, can_delete=False)

	if request.method == 'POST':
		questionForm = QuestionForm(request.POST, request.FILES, instance=question, prefix="main")
		choiceInlineFormSet = ChoiceInlineFormSet(request.POST, request.FILES, instance=question, prefix="nested")

		if questionForm.is_valid() and choiceInlineFormSet.is_valid():
			questionForm.save()
			choiceInlineFormSet.save()
		else:
			return render(request, 'polls/new.html', {'questionForm': questionForm, 'formset': choiceInlineFormSet})
	else:
		questionForm = QuestionForm(instance=question, prefix="main")
		choiceInlineFormSet = ChoiceInlineFormSet(instance=question, prefix="nested")
	return render(request, 'polls/new.html', {'questionForm': questionForm, 'formset': choiceInlineFormSet})

"""
class DeleteView(DeleteView):
	model = Question()
	success_url = reverse('polls:index', args=())
"""

mysite/polls/templates/polls/base.html
{% load staticfiles %}

<html>
	<head>
		<title>Django application</title>
	</head>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
	<body>
		<header>
			<h1>{% block header_title %}{% endblock %}</h1>
		</header>
		{% block content %}{% endblock %}
	</body>
	<footer>
		{% block footer %}{% endblock %}
		<h4>Pié de pàgina</h4>
	</footer>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block header_title %}{{question.question_text}}{% endblock %}

{% block content %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="{% url 'polls:vote' question.id %}" method="post">
		{% csrf_token %}

		<h2 class="subtitle">List of choices</h2>
		{% for choice in question.choice_set.all %}
			<div class="container">
			    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" 
			    	{% if forloop.counter == 1%}checked="checked"{% endif %}
			    />
			    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		    </div>
		{% endfor %}
		<div class="container">
			<input class="btn left" type="submit" value="Vote" />
		</div>
	</form>

	<a class="btn" href="{% url 'polls:update' question.id %}">update</a>

	<a class="btn" href="{% url 'polls:delete' question.id %}">delete</a>

{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block header_title %}all Questions{% endblock %}

{% block content %}
	<div class="container">
		{% if latest_question_list %}
		    {% for question in latest_question_list %}
		    	<a href="{% url 'polls:detail' question.id %}">
					<div class="question">
						{{ question.question_text }}
					</div>
		    	</a>
		    {% endfor %}
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
	</div>

	<div class="container">
		<input id="btn_new_question" class="btn red left" type="button" value="Create a new Question">
		<script>
			document.getElementById("btn_new_question").addEventListener("click", function(){
			    window.location = "{% url 'polls:new' %}";
			});
		</script>
	</div>
{% endblock %}

mysite/polls/templates/polls/new.html
<div class="container">
	<form action="" method="post">
		{% csrf_token %}

		<h2 class="subtitle">Question</h2>
		{% for field in questionForm.visible_fields %}
			<div class="field">
				<label class="label">{{ field.label }}:</label>
				<input id="{{ field.html_name }}" name="{{ field.html_name }}" type="text" value="">
				<label class="error">{{ field.errors  }}</label>
			</div>
		{% endfor %}

		{{formset.management_form}}
		{% for form in formset %}
			{% for field in form.visible_fields %}
				<div class="field">
					<label class="label">{{ field.label }}:</label>
					<input id="{{ field.html_name }}" name="{{ field.html_name }}" type="text" value="">
					<label class="error">{{ field.errors  }}</label>
				</div>
			{% endfor %}
		{% endfor %}

		<input type="submit" value="Submit" class="btn">

	</form>
</div>

mysite/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block header_title %}{{question.question_text}}{% endblock %}

{% block content %}

	{% for choice in question.choice_set.all %}
		<a href="{% url 'polls:detail' question.id %}">
			<div>
				{{ question.question_text }} -- {{ choice.votes }} has vote{{ choice.votes|pluralize }}
			</div>
		</a>
	{% endfor %}

	<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}

mysite/polls/templates/polls/update.html
{% extends "base.html" %}
{% block content %}

<div class="container">
	<form action="" method="post">
		{% csrf_token %}

		<div class="field">
			<label class="label">Description:</label>
			<input id="question_text" name="question_text" type="text" value="{% if form.question_text.value != None %}{{form.question_text.value}}{% endif %}">
			{{ form.question_text.errors }}
		</div>

		<input type="submit" value="Update" class="btn">
	</form>
</div>

{% endblock %}